# Generated by Django 5.0.6 on 2024-08-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
    ]
