# Generated by Django 5.0.6 on 2024-07-17 13:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateTimeField()),
                ("target_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("To do", "To do"),
                            ("In progress", "In progress"),
                            ("Done", "Done"),
                        ],
                        default="To do",
                        max_length=11,
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_goals",
                        to="goals.goal",
                    ),
                ),
            ],
        ),
    ]
