# Generated by Django 5.0.6 on 2024-08-07 10:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="observation",
            unique_together={("user", "observation")},
        ),
    ]
